USE [master]
GO

ALTER DATABASE [tempdb] MODIFY FILE ( NAME = tempdev , FILENAME = 'C:\SQL\DATA\tempdev.mdf' );
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = templog , FILENAME = 'N:\SQL\LOG\templog.ldf' );

ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdb1', FILENAME = N'O:\SQL\DATA\tempdb1.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdb2', FILENAME = N'P:\SQL\DATA\tempdb2.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdb3', FILENAME = N'Q:\SQL\DATA\tempdb3.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdb4', FILENAME = N'R:\SQL\DATA\tempdb4.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdb5', FILENAME = N'S:\SQL\DATA\tempdb5.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdb6', FILENAME = N'T:\SQL\DATA\tempdb6.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdb7', FILENAME = N'U:\SQL\DATA\tempdb7.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'tempdb8', FILENAME = N'V:\SQL\DATA\tempdb8.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
